### ISSUE TITLE
something is wrong

### ISSUE THREAD

**Issue by minsuoqingcheng** [wufan-tb/AutoLabelImg#2]
![image](https://user-images.githubusercontent.com/11973915/165213722-e49b0edc-7a1b-4a61-8dc0-e6a862117826.png)

替换成最新的YOLOv5代码，并下载了模型，选择标签后提示如上图所示，请问是什么原因？

**Comment by wufan-tb** [comment]
具体是哪一步报错的，要不你参考下我录的视频，https://www.bilibili.com/video/BV1Uu411Q7WW/  如果操作顺序一样的话，可能是不支持新模型

**Comment by minsuoqingcheng** [comment]
你好，是在选完模型以及标签、确定后图片大小后，开始报错的。请问你用的YOLO哪个版本

**Comment by wufan-tb** [comment]
2.0版本的

**Comment by minsuoqingcheng** [comment]
你好，我把模型换成YOLOV5 2.0版本后，上面的问题解决了，但是遇到了下面的问题
![image](https://user-images.githubusercontent.com/11973915/165237290-bbfc21b3-baa1-4d4a-9a5b-384be346611f.png)
我查看label_info，发现也是同样的报错，应该是标注保存的路径没有指定，但是我在界面上没有发现提前指定标注路径保存路径的入口，请问是需要到代码里面指定吗？

**Comment by wufan-tb** [comment]
有的，左边那个open xml

**Comment by minsuoqingcheng** [comment]
可以了，多谢，我之前用的版本这个叫change_save_dir

**Comment by wufan-tb** [comment]
是的，为了方便排版，名字改短了

**Comment by kimkimyoung** [comment]
@

> ![image](https://user-images.githubusercontent.com/11973915/165213722-e49b0edc-7a1b-4a61-8dc0-e6a862117826.png)
> 
> 替换成最新的YOLOv5代码，并下载了模型，选择标签后提示如上图所示，请问是什么原因？

不是用不了新版本，而是要修改labelImg.py第2432行，因为新版本这个dataset 返回5个值。另外如果要修改新版本还有几个地方需要改，和这个问题类似。
`for path, img, im0s, vid_cap in dataset:` 
改为 `for path, img, im0s, vid_cap, msg in dataset:`
