### ISSUE TITLE
系统支持

### ISSUE THREAD

**Issue by mikasazgx** [wufan-tb/AutoLabelImg#7]
只提供了ubuntu编译和windows编译
是否支持mac

**Comment by wufan-tb** [comment]
mac我没有实际跑过，但是应该是支持的，可以参考原版labelimg的安装流程

**Comment by suay1113** [comment]
https://github.com/wufan-tb/AutoLabelImg/blob/master/labelImg.py#L2336
device = torch_utils.select_device('cpu')

can be used in macOS with pytorch-cpu version >= 1.7.0
